<?php
$catalogue = require __DIR__ . '/products.php';
$p = $catalogue['KUKA KRL G-Code Post-Processor'];
?><!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>JBY Solutions - KUKA KRL G-Code Post-Processor</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>

  <header></header>
  <main>
    <section class="product-detail-section">

      <!-- Back link -->
      <a class="back-link" href="webshop.php">&#8592; Back to Shop</a>

      <!-- Hero -->
      <div class="product-detail-hero">
        <div class="product-detail-info">
          <h1>KUKA KRL G-Code Post-Processor</h1>
          <p class="product-detail-tagline">
            Bridge the gap between CAM and your KUKA robot — output native KRL from any G-Code toolpath.
          </p>
          <span class="product-price product-price-lg"><?= htmlspecialchars($p['display']) ?></span>
          <button class="btn-primary btn-buy btn-detail-buy"
                  data-product="KUKA KRL G-Code Post-Processor"
                  data-price="<?= htmlspecialchars($p['display']) ?>">
            Buy Now
          </button>
        </div>

        <!-- Placeholder hero image -->
        <div class="product-detail-image">
          <svg viewBox="0 0 560 340" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%">
            <rect width="560" height="340" rx="12" fill="#1e293b"/>
            <!-- Window chrome -->
            <rect x="0" y="0" width="560" height="32" rx="12" fill="#0f172a"/>
            <rect x="12" y="11" width="10" height="10" rx="5" fill="#ef4444"/>
            <rect x="30" y="11" width="10" height="10" rx="5" fill="#f59e0b"/>
            <rect x="48" y="11" width="10" height="10" rx="5" fill="#22c55e"/>
            <text x="80" y="22" font-family="monospace" font-size="11" fill="#94a3b8">kuka-post-processor — R1/Program/milling_op.src</text>
            <!-- SRC file -->
            <text x="20" y="58"  font-family="monospace" font-size="12" fill="#64748b">; Generated by JBY KUKA Post-Processor</text>
            <text x="20" y="76"  font-family="monospace" font-size="12"><tspan fill="#f472b6">DEF</tspan><tspan fill="#e2e8f0"> milling_op()</tspan></text>
            <text x="20" y="94"  font-family="monospace" font-size="12" fill="#64748b">  ; --- Init ---</text>
            <text x="20" y="112" font-family="monospace" font-size="12"><tspan fill="#38bdf8">  BAS</tspan><tspan fill="#e2e8f0"> (#INITMOV, 0)</tspan></text>
            <text x="20" y="130" font-family="monospace" font-size="12"><tspan fill="#38bdf8">  $TOOL</tspan><tspan fill="#e2e8f0"> = TOOL_DATA[1]</tspan></text>
            <text x="20" y="148" font-family="monospace" font-size="12"><tspan fill="#38bdf8">  $BASE</tspan><tspan fill="#e2e8f0"> = BASE_DATA[1]</tspan></text>
            <text x="20" y="166" font-family="monospace" font-size="12" fill="#64748b">  ; --- Move to safe pos ---</text>
            <text x="20" y="184" font-family="monospace" font-size="12"><tspan fill="#a78bfa">  PTP</tspan><tspan fill="#e2e8f0"> HOME </tspan><tspan fill="#f472b6">Vel</tspan><tspan fill="#e2e8f0">=100% </tspan><tspan fill="#f472b6">PDAT</tspan><tspan fill="#e2e8f0">1</tspan></text>
            <text x="20" y="202" font-family="monospace" font-size="12" fill="#64748b">  ; --- Approach ---</text>
            <text x="20" y="220" font-family="monospace" font-size="12"><tspan fill="#a78bfa">  LIN</tspan><tspan fill="#e2e8f0"> {X 0.0, Y 0.0, Z 50.0, A 0.0, B -90.0, C 0.0} </tspan><tspan fill="#f472b6">Vel</tspan><tspan fill="#e2e8f0">=0.5 m/s</tspan></text>
            <text x="20" y="238" font-family="monospace" font-size="12"><tspan fill="#a78bfa">  LIN</tspan><tspan fill="#e2e8f0"> {X 0.0, Y 0.0, Z -1.0} </tspan><tspan fill="#f472b6">Vel</tspan><tspan fill="#e2e8f0">=0.1 m/s</tspan></text>
            <text x="20" y="256" font-family="monospace" font-size="12"><tspan fill="#a78bfa">  LIN</tspan><tspan fill="#e2e8f0"> {X 50.0, Y 0.0, Z -1.0} </tspan><tspan fill="#f472b6">Vel</tspan><tspan fill="#e2e8f0">=0.3 m/s</tspan></text>
            <text x="20" y="274" font-family="monospace" font-size="12"><tspan fill="#a78bfa">  LIN</tspan><tspan fill="#e2e8f0"> {X 50.0, Y 30.0, Z -1.0} </tspan><tspan fill="#f472b6">Vel</tspan><tspan fill="#e2e8f0">=0.3 m/s</tspan></text>
            <text x="20" y="292" font-family="monospace" font-size="12"><tspan fill="#a78bfa">  PTP</tspan><tspan fill="#e2e8f0"> HOME </tspan><tspan fill="#f472b6">Vel</tspan><tspan fill="#e2e8f0">=100% </tspan><tspan fill="#f472b6">PDAT</tspan><tspan fill="#e2e8f0">1</tspan></text>
            <text x="20" y="310" font-family="monospace" font-size="12"><tspan fill="#f472b6">END</tspan></text>
            <rect x="20" y="318" width="8" height="14" rx="1" fill="#a78bfa" opacity="0.8"/>
          </svg>
        </div>
      </div>

      <!-- Description -->
      <div class="product-detail-body">
        <div class="product-detail-main">
          <h2>What is it?</h2>
          <p>
            The JBY KUKA KRL G-Code Post-Processor converts standard G-Code toolpaths — typically
            produced by CAM software — into KUKA Robot Language (KRL), so you can run CNC-style
            machining programs directly on a KUKA industrial robot arm without manually rewriting
            the code.
          </p>
          <p>
            The output consists of a pair of native KRL files (.SRC + .DAT) that can be loaded
            straight onto a KRC4 or KRC5 controller. Motion types, velocities, tool and base
            frame references, and approximation zones are all mapped automatically.
          </p>

          <h2>Features</h2>
          <ul class="feature-list">
            <li>
              <span class="feature-icon">&#10003;</span>
              <span>Outputs native KRL .SRC and .DAT file pairs</span>
            </li>
            <li>
              <span class="feature-icon">&#10003;</span>
              <span>Maps G0 rapid moves to PTP and G1/G2/G3 to LIN / CIRC motion</span>
            </li>
            <li>
              <span class="feature-icon">&#10003;</span>
              <span>Configurable tool frame ($TOOL) and base frame ($BASE) references</span>
            </li>
            <li>
              <span class="feature-icon">&#10003;</span>
              <span>Automatic approximation zone (C_DIS / C_VEL) handling for smooth paths</span>
            </li>
            <li>
              <span class="feature-icon">&#10003;</span>
              <span>E6POS Cartesian coordinate mapping with orientation support</span>
            </li>
            <li>
              <span class="feature-icon">&#10003;</span>
              <span>Feed rate conversion from mm/min to m/s (KRL native units)</span>
            </li>
            <li>
              <span class="feature-icon">&#10003;</span>
              <span>Compatible with KRC4 and KRC5 controllers</span>
            </li>
            <li>
              <span class="feature-icon">&#10003;</span>
              <span>Command-line interface — scriptable and CI/CD friendly</span>
            </li>
          </ul>

          <!-- Placeholder workflow image -->
          <h2>Workflow</h2>
          <div class="placeholder-image">
            <svg viewBox="0 0 700 160" xmlns="http://www.w3.org/2000/svg" width="100%">
              <rect width="700" height="160" rx="10" fill="#f1f5f9"/>
              <rect x="20"  y="50" width="140" height="60" rx="8" fill="#dbeafe" stroke="#93c5fd" stroke-width="1.5"/>
              <text x="90"  y="78"  text-anchor="middle" font-family="system-ui" font-size="13" font-weight="600" fill="#1e40af">CAM Software</text>
              <text x="90"  y="96"  text-anchor="middle" font-family="system-ui" font-size="11" fill="#3b82f6">G-Code export</text>

              <text x="195" y="84" text-anchor="middle" font-family="system-ui" font-size="22" fill="#94a3b8">&#8594;</text>

              <rect x="220" y="50" width="140" height="60" rx="8" fill="#2563eb" stroke="#1d4ed8" stroke-width="1.5"/>
              <text x="290" y="78"  text-anchor="middle" font-family="system-ui" font-size="13" font-weight="600" fill="#fff">JBY KUKA</text>
              <text x="290" y="96"  text-anchor="middle" font-family="system-ui" font-size="13" font-weight="600" fill="#fff">Post-Processor</text>

              <text x="395" y="84" text-anchor="middle" font-family="system-ui" font-size="22" fill="#94a3b8">&#8594;</text>

              <rect x="420" y="50" width="140" height="60" rx="8" fill="#ede9fe" stroke="#c4b5fd" stroke-width="1.5"/>
              <text x="490" y="75"  text-anchor="middle" font-family="system-ui" font-size="13" font-weight="600" fill="#5b21b6">KRL Files</text>
              <text x="490" y="92"  text-anchor="middle" font-family="system-ui" font-size="11" fill="#7c3aed">.SRC + .DAT</text>

              <text x="595" y="84" text-anchor="middle" font-family="system-ui" font-size="22" fill="#94a3b8">&#8594;</text>

              <rect x="620" y="50" width="60" height="60" rx="8" fill="#f3f4f6" stroke="#d1d5db" stroke-width="1.5"/>
              <text x="650" y="75"  text-anchor="middle" font-family="system-ui" font-size="11" font-weight="600" fill="#374151">KUKA</text>
              <text x="650" y="90"  text-anchor="middle" font-family="system-ui" font-size="11" fill="#6b7280">Robot</text>
              <text x="650" y="105" text-anchor="middle" font-family="system-ui" font-size="11" fill="#6b7280">KRC4/5</text>
            </svg>
          </div>
        </div>

        <!-- Sidebar -->
        <aside class="product-detail-aside">
          <div class="aside-card">
            <h3>In the box</h3>
            <ul class="aside-list">
              <li>Post-processor executable (Windows / macOS / Linux)</li>
              <li>Default config file (tool &amp; base frame mappings)</li>
              <li>Documentation &amp; quick-start guide</li>
              <li>Example .SRC / .DAT output files</li>
              <li>Lifetime updates</li>
            </ul>
          </div>
          <div class="aside-card">
            <h3>Requirements</h3>
            <ul class="aside-list">
              <li>Windows 10+ / macOS 12+ / Ubuntu 20+</li>
              <li>KUKA KRC4 or KRC5 controller</li>
              <li>Any CAM software that exports standard G-Code</li>
            </ul>
          </div>
          <div class="aside-card aside-buy">
            <span class="product-price"><?= htmlspecialchars($p['display']) ?></span>
            <p>One-time purchase. No subscription.</p>
            <button class="btn-primary btn-buy btn-large shop-submit"
                    data-product="KUKA KRL G-Code Post-Processor"
                    data-price="<?= htmlspecialchars($p['display']) ?>">
              Buy Now
            </button>
          </div>
        </aside>
      </div>

    </section>

    <!-- Checkout modal -->
    <div id="checkout-modal" class="modal-overlay" hidden>
      <div class="modal-box">
        <button class="modal-close" id="modal-close" aria-label="Close">&times;</button>
        <h2>Complete your order</h2>
        <p id="modal-product-label" class="modal-product-name"></p>

        <!-- Step 1: Contact details -->
        <div id="step-contact">
          <form id="checkout-form" novalidate>
            <input type="hidden" id="order-product" name="product" />
            <input type="hidden" id="order-price"   name="price"   />
            <div class="form-group">
              <label for="order-name">Full Name</label>
              <input type="text"  id="order-name"  name="name"  autocomplete="name" />
            </div>
            <div class="form-group">
              <label for="order-email">Email Address</label>
              <input type="email" id="order-email" name="email" autocomplete="email" />
            </div>
            <ul id="order-errors" class="error-list" hidden></ul>
            <button type="submit" class="btn-primary btn-large shop-submit" id="order-submit">
              Continue to Payment
            </button>
          </form>
        </div>

        <!-- Step 2: Payment -->
        <div id="step-payment" hidden>
          <button class="payment-back-btn" id="back-to-contact">&#8592; Edit details</button>
          <div class="payment-summary-box">
            Paying for: <strong id="payment-summary-text"></strong>
          </div>
          <div id="paypal-button-container"></div>
        </div>

        <!-- Success -->
        <div id="order-success" class="success-section" hidden>
          <div class="success-content">
            <svg class="success-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <circle cx="12" cy="12" r="10"/><path d="M9 12l2 2 4-4"/>
            </svg>
            <h3>Payment confirmed!</h3>
            <p>Thanks for your purchase. We'll send your download link and invoice to your email shortly.</p>
            <button class="btn-primary" id="modal-done">Close</button>
          </div>
        </div>

      </div>
    </div>
  </main>
  <footer></footer>

  <script src="main.js"></script>
  <script>document.getElementById("year").textContent = new Date().getFullYear();</script>
  <script src="inject-shared.js"></script>
  <script src="https://www.paypal.com/sdk/js?client-id=AezzTHzS_1xMbOkSrdrQlQW7haRJz_Q2j1ZOtZqXy4ycN-2a7u1Es0hY8cj_lVhSMW8aRdzDIryWNmDC&currency=EUR&intent=capture"></script>
  <script src="webshop.js"></script>
</body>
</html>
